### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by wowkin2** [cr0hn/aiohttp-cache#3]
```python
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/venv/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/venv/lib/python3.6/site-packages/aiohttp_cache/middleware.py", line 16, in middleware_handler
    key = cache_backend.make_key(request)
  File "/venv/lib/python3.6/site-packages/aiohttp_cache/backends.py", line 38, in make_key
    postdata="".join(request.post()),
TypeError: can only join an iterable
```
Found a bug will do a PR

**Comment by wowkin2** [comment]
@cr0hn, please review PR https://github.com/cr0hn/aiohttp-cache/pull/4

**Comment by wowkin2** [comment]
@cr0hn, I see you merged my PR, but I don't see version 1.0.3 on PyPi, can you build it or setup CI for that.
p.s. need to update `Readme.rst` file with the newest version.

**Comment by cr0hn** [comment]
Just added C.I. with CircleCI and check that it works. 

New version is now on PyPi.

Thx for the PR :)

**Comment by cr0hn** [comment]
Please, check it and close the issue if the problem was solved
